on: [push,pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Convert Scripts
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd $GITHUB_WORKSPACE/../
          mkdir scripts
          cp -r $GITHUB_WORKSPACE scripts/story
      - uses: actions/checkout@v2
        with:
          repository: infinite-whys/whispers-scripts
          token: ${{ secrets.BOT_PAT }}
      - run: |
          rm -rf $GITHUB_WORKSPACE/scripts
          cd $GITHUB_WORKSPACE
          mv $GITHUB_WORKSPACE/../scripts $GITHUB_WORKSPACE/
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: Converting scripts to json
        run: npm start
      - name: Archive json artifacts
        uses: actions/upload-artifact@v2
        with:
          name: All json files
          path: |
            scripts/**/*.json
      - name: Updating sheets in Google Cloud Storage
        run: npm run sheets2tsv
        env:
          GCP_KEY: ${{ secrets.GCP_KEY }}
          GCP_ID: ${{ secrets.GCP_ID }}
          SCRIPT_KEY: ${{ secrets.SCRIPT_KEY }}
          SHEET_ID: ${{ secrets.SHEET_ID }}